/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as SignedInRouteImport } from './routes/_signedIn'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as GuestForgotPasswordRouteImport } from './routes/_guest/forgot-password'
import { Route as GuestSignInRouteImport } from './routes/_guest/sign-in'
import { Route as GuestSignUpRouteImport } from './routes/_guest/sign-up'
import { Route as SignedInIndexRouteImport } from './routes/_signedIn/index'
import { Route as SignedInCronicaRouteImport } from './routes/_signedIn/cronica'
import { Route as SignedInMapaIndexRouteImport } from './routes/_signedIn/mapa.index'
import { Route as SignedInMapaProvinceRouteImport } from './routes/_signedIn/mapa.$province'

const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const SignedInRoute = SignedInRouteImport.update({
  id: '/_signedIn',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestForgotPasswordRoute = GuestForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => GuestRoute,
} as any)
const GuestSignInRoute = GuestSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => GuestRoute,
} as any)
const GuestSignUpRoute = GuestSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => GuestRoute,
} as any)
const SignedInIndexRoute = SignedInIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SignedInRoute,
} as any)
const SignedInCronicaRoute = SignedInCronicaRouteImport.update({
  id: '/cronica',
  path: '/cronica',
  getParentRoute: () => SignedInRoute,
} as any)
const SignedInMapaIndexRoute = SignedInMapaIndexRouteImport.update({
  id: '/mapa/',
  path: '/mapa/',
  getParentRoute: () => SignedInRoute,
} as any)
const SignedInMapaProvinceRoute = SignedInMapaProvinceRouteImport.update({
  id: '/mapa/$province',
  path: '/mapa/$province',
  getParentRoute: () => SignedInRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SignedInIndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/forgot-password': typeof GuestForgotPasswordRoute
  '/sign-in': typeof GuestSignInRoute
  '/sign-up': typeof GuestSignUpRoute
  '/cronica': typeof SignedInCronicaRoute
  '/mapa/$province': typeof SignedInMapaProvinceRoute
  '/mapa/': typeof SignedInMapaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof SignedInIndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/forgot-password': typeof GuestForgotPasswordRoute
  '/sign-in': typeof GuestSignInRoute
  '/sign-up': typeof GuestSignUpRoute
  '/cronica': typeof SignedInCronicaRoute
  '/mapa/$province': typeof SignedInMapaProvinceRoute
  '/mapa': typeof SignedInMapaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_guest': typeof GuestRouteWithChildren
  '/_signedIn': typeof SignedInRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_guest/forgot-password': typeof GuestForgotPasswordRoute
  '/_guest/sign-in': typeof GuestSignInRoute
  '/_guest/sign-up': typeof GuestSignUpRoute
  '/_signedIn/cronica': typeof SignedInCronicaRoute
  '/_signedIn/': typeof SignedInIndexRoute
  '/_signedIn/mapa/$province': typeof SignedInMapaProvinceRoute
  '/_signedIn/mapa/': typeof SignedInMapaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reset-password'
    | '/verify-email'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/cronica'
    | '/mapa/$province'
    | '/mapa/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/verify-email'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/cronica'
    | '/mapa/$province'
    | '/mapa'
  id:
    | '__root__'
    | '/_guest'
    | '/_signedIn'
    | '/reset-password'
    | '/verify-email'
    | '/_guest/forgot-password'
    | '/_guest/sign-in'
    | '/_guest/sign-up'
    | '/_signedIn/cronica'
    | '/_signedIn/'
    | '/_signedIn/mapa/$province'
    | '/_signedIn/mapa/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  GuestRoute: typeof GuestRouteWithChildren
  SignedInRoute: typeof SignedInRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_signedIn': {
      id: '/_signedIn'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SignedInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/forgot-password': {
      id: '/_guest/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof GuestForgotPasswordRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/sign-in': {
      id: '/_guest/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof GuestSignInRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/sign-up': {
      id: '/_guest/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof GuestSignUpRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_signedIn/': {
      id: '/_signedIn/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SignedInIndexRouteImport
      parentRoute: typeof SignedInRoute
    }
    '/_signedIn/cronica': {
      id: '/_signedIn/cronica'
      path: '/cronica'
      fullPath: '/cronica'
      preLoaderRoute: typeof SignedInCronicaRouteImport
      parentRoute: typeof SignedInRoute
    }
    '/_signedIn/mapa/': {
      id: '/_signedIn/mapa/'
      path: '/mapa'
      fullPath: '/mapa/'
      preLoaderRoute: typeof SignedInMapaIndexRouteImport
      parentRoute: typeof SignedInRoute
    }
    '/_signedIn/mapa/$province': {
      id: '/_signedIn/mapa/$province'
      path: '/mapa/$province'
      fullPath: '/mapa/$province'
      preLoaderRoute: typeof SignedInMapaProvinceRouteImport
      parentRoute: typeof SignedInRoute
    }
  }
}

interface GuestRouteChildren {
  GuestForgotPasswordRoute: typeof GuestForgotPasswordRoute
  GuestSignInRoute: typeof GuestSignInRoute
  GuestSignUpRoute: typeof GuestSignUpRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestForgotPasswordRoute: GuestForgotPasswordRoute,
  GuestSignInRoute: GuestSignInRoute,
  GuestSignUpRoute: GuestSignUpRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

interface SignedInRouteChildren {
  SignedInCronicaRoute: typeof SignedInCronicaRoute
  SignedInIndexRoute: typeof SignedInIndexRoute
  SignedInMapaProvinceRoute: typeof SignedInMapaProvinceRoute
  SignedInMapaIndexRoute: typeof SignedInMapaIndexRoute
}

const SignedInRouteChildren: SignedInRouteChildren = {
  SignedInCronicaRoute: SignedInCronicaRoute,
  SignedInIndexRoute: SignedInIndexRoute,
  SignedInMapaProvinceRoute: SignedInMapaProvinceRoute,
  SignedInMapaIndexRoute: SignedInMapaIndexRoute,
}

const SignedInRouteWithChildren = SignedInRoute._addFileChildren(
  SignedInRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  GuestRoute: GuestRouteWithChildren,
  SignedInRoute: SignedInRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
